// <auto-generated />
using System;
using EscritorioVirtual.Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EscritorioVirtual.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260928220131_CreateTable_Workspace")]
    partial class CreateTable_Workspace
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("EscritorioVirtual.Domain.AggregateRoot.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("UsuarioAtualizacaoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioCriacaoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UsuarioAtualizacaoId");

                    b.HasIndex("UsuarioCriacaoId");

                    b.ToTable("Users", "public");
                });

            modelBuilder.Entity("EscritorioVirtual.Domain.AggregateRoot.Workspaces.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasComment("Identificador UUID do Workspace / Não Nulo / LGPD: dado não sensível");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("Data de criação / Não Nulo / LGPD: dado não sensível");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("Nome da empresa / organização / Não Nulo / LGPD: dado não sensível");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Slug amigável para URL / Não Nulo / LGPD: dado não sensível");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid?>("UsuarioAtualizacaoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioCriacaoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("UsuarioAtualizacaoId");

                    b.HasIndex("UsuarioCriacaoId");

                    b.ToTable("Workspaces", "public", t =>
                        {
                            t.HasComment("Tabela responsável por armazenar workspaces/organizações da plataforma");
                        });
                });

            modelBuilder.Entity("EscritorioVirtual.Domain.Aggregates.Workspaces.WorkspaceInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasComment("Identificador UUID do convite / Não Nulo / LGPD: dado não sensível");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Código único do convite / Não Nulo / LGPD: dado não sensível");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("Data de geração do convite / Não Nulo / LGPD: dado não sensível");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasComment("ID do usuário criador / Não Nulo / LGPD: dado não sensível");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("E-mail destinatário (opcional) / Nulo / LGPD: dado não sensível");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("Data de expiração / Nulo / LGPD: dado não sensível");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasComment("Status ativo / Não Nulo / LGPD: dado não sensível");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasComment("Papel atribuído / Não Nulo / LGPD: dado não sensível");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasComment("ID do Workspace / Não Nulo / LGPD: dado não sensível");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("WorkspaceInvites", "public", t =>
                        {
                            t.HasComment("Tabela responsável por armazenar convites para acesso ao Workspace");
                        });
                });

            modelBuilder.Entity("EscritorioVirtual.Domain.Aggregates.Workspaces.WorkspaceUser", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasComment("ID do Workspace / Não Nulo / LGPD: dado não sensível");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasComment("ID do Usuário / Não Nulo / LGPD: dado não sensível");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("Data de ingresso no Workspace / Não Nulo / LGPD: dado não sensível");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasComment("Papel do usuário (1=Owner, 2=Admin, 3=Member, 4=Guest) / Não Nulo / LGPD: dado não sensível");

                    b.HasKey("WorkspaceId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("WorkspaceUsers", "public", t =>
                        {
                            t.HasComment("Tabela responsável por armazenar vínculo entre usuários e workspaces");
                        });
                });

            modelBuilder.Entity("EscritorioVirtual.Domain.AggregateRoot.Usuario", b =>
                {
                    b.HasOne("EscritorioVirtual.Domain.AggregateRoot.Usuario", "UsuarioAtualizacao")
                        .WithMany()
                        .HasForeignKey("UsuarioAtualizacaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EscritorioVirtual.Domain.AggregateRoot.Usuario", "UsuarioCriacao")
                        .WithMany()
                        .HasForeignKey("UsuarioCriacaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UsuarioAtualizacao");

                    b.Navigation("UsuarioCriacao");
                });

            modelBuilder.Entity("EscritorioVirtual.Domain.AggregateRoot.Workspaces.Workspace", b =>
                {
                    b.HasOne("EscritorioVirtual.Domain.AggregateRoot.Usuario", "UsuarioAtualizacao")
                        .WithMany()
                        .HasForeignKey("UsuarioAtualizacaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EscritorioVirtual.Domain.AggregateRoot.Usuario", "UsuarioCriacao")
                        .WithMany()
                        .HasForeignKey("UsuarioCriacaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UsuarioAtualizacao");

                    b.Navigation("UsuarioCriacao");
                });

            modelBuilder.Entity("EscritorioVirtual.Domain.Aggregates.Workspaces.WorkspaceInvite", b =>
                {
                    b.HasOne("EscritorioVirtual.Domain.AggregateRoot.Usuario", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EscritorioVirtual.Domain.AggregateRoot.Workspaces.Workspace", "Workspace")
                        .WithMany("Invites")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("EscritorioVirtual.Domain.Aggregates.Workspaces.WorkspaceUser", b =>
                {
                    b.HasOne("EscritorioVirtual.Domain.AggregateRoot.Usuario", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EscritorioVirtual.Domain.AggregateRoot.Workspaces.Workspace", "Workspace")
                        .WithMany("Members")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("EscritorioVirtual.Domain.AggregateRoot.Workspaces.Workspace", b =>
                {
                    b.Navigation("Invites");

                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
