// <auto-generated />
using System;
using EscritorioVirtual.Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EscritorioVirtual.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260928232145_AddChatChannelsAndMessages")]
    partial class AddChatChannelsAndMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("EscritorioVirtual.Domain.AggregateRoot.Chat.ChatChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ChannelType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("UsuarioAtualizacaoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioCriacaoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ZoneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioAtualizacaoId");

                    b.HasIndex("UsuarioCriacaoId");

                    b.HasIndex("WorkspaceId");

                    b.HasIndex("WorkspaceId", "ChannelType");

                    b.ToTable("ChatChannels", "public");
                });

            modelBuilder.Entity("EscritorioVirtual.Domain.AggregateRoot.Maps.Map", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("GridHeight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100);

                    b.Property<int>("GridWidth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100);

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<int>("TileSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(32);

                    b.Property<string>("TiledMapData")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("UsuarioAtualizacaoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioCriacaoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioAtualizacaoId");

                    b.HasIndex("UsuarioCriacaoId");

                    b.ToTable("Maps", "public");
                });

            modelBuilder.Entity("EscritorioVirtual.Domain.AggregateRoot.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarConfig")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("UsuarioAtualizacaoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioCriacaoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UsuarioAtualizacaoId");

                    b.HasIndex("UsuarioCriacaoId");

                    b.ToTable("Users", "public");
                });

            modelBuilder.Entity("EscritorioVirtual.Domain.AggregateRoot.Workspaces.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasComment("Identificador UUID do Workspace / Não Nulo / LGPD: dado não sensível");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("Data de criação / Não Nulo / LGPD: dado não sensível");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("Nome da empresa / organização / Não Nulo / LGPD: dado não sensível");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Slug amigável para URL / Não Nulo / LGPD: dado não sensível");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid?>("UsuarioAtualizacaoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioCriacaoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("UsuarioAtualizacaoId");

                    b.HasIndex("UsuarioCriacaoId");

                    b.ToTable("Workspaces", "public", t =>
                        {
                            t.HasComment("Tabela responsável por armazenar workspaces/organizações da plataforma");
                        });
                });

            modelBuilder.Entity("EscritorioVirtual.Domain.Aggregates.Chat.ChatChannelMember", b =>
                {
                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("LastReadAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("ChannelId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatChannelMembers", "public");
                });

            modelBuilder.Entity("EscritorioVirtual.Domain.Aggregates.Chat.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId", "CreatedAt");

                    b.ToTable("Messages", "public");
                });

            modelBuilder.Entity("EscritorioVirtual.Domain.Aggregates.Maps.MapObject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("CoordX")
                        .HasColumnType("integer");

                    b.Property<int>("CoordY")
                        .HasColumnType("integer");

                    b.Property<bool>("IsSolid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("MapId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rotation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("ZIndexOffset")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("MapId");

                    b.ToTable("MapObjects", "public");
                });

            modelBuilder.Entity("EscritorioVirtual.Domain.Aggregates.Maps.MapZone", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer");

                    b.Property<int>("EndX")
                        .HasColumnType("integer");

                    b.Property<int>("EndY")
                        .HasColumnType("integer");

                    b.Property<Guid>("MapId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("StartX")
                        .HasColumnType("integer");

                    b.Property<int>("StartY")
                        .HasColumnType("integer");

                    b.Property<string>("ZoneType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("MapId");

                    b.ToTable("MapZones", "public");
                });

            modelBuilder.Entity("EscritorioVirtual.Domain.Aggregates.Workspaces.WorkspaceInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasComment("Identificador UUID do convite / Não Nulo / LGPD: dado não sensível");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Código único do convite / Não Nulo / LGPD: dado não sensível");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("Data de geração do convite / Não Nulo / LGPD: dado não sensível");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasComment("ID do usuário criador / Não Nulo / LGPD: dado não sensível");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("E-mail destinatário (opcional) / Nulo / LGPD: dado não sensível");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("Data de expiração / Nulo / LGPD: dado não sensível");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasComment("Status ativo / Não Nulo / LGPD: dado não sensível");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasComment("Papel atribuído / Não Nulo / LGPD: dado não sensível");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasComment("ID do Workspace / Não Nulo / LGPD: dado não sensível");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("WorkspaceInvites", "public", t =>
                        {
                            t.HasComment("Tabela responsável por armazenar convites para acesso ao Workspace");
                        });
                });

            modelBuilder.Entity("EscritorioVirtual.Domain.Aggregates.Workspaces.WorkspaceUser", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasComment("ID do Workspace / Não Nulo / LGPD: dado não sensível");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasComment("ID do Usuário / Não Nulo / LGPD: dado não sensível");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("Data de ingresso no Workspace / Não Nulo / LGPD: dado não sensível");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasComment("Papel do usuário (1=Owner, 2=Admin, 3=Member, 4=Guest) / Não Nulo / LGPD: dado não sensível");

                    b.HasKey("WorkspaceId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("WorkspaceUsers", "public", t =>
                        {
                            t.HasComment("Tabela responsável por armazenar vínculo entre usuários e workspaces");
                        });
                });

            modelBuilder.Entity("EscritorioVirtual.Domain.AggregateRoot.Chat.ChatChannel", b =>
                {
                    b.HasOne("EscritorioVirtual.Domain.AggregateRoot.Usuario", "UsuarioAtualizacao")
                        .WithMany()
                        .HasForeignKey("UsuarioAtualizacaoId");

                    b.HasOne("EscritorioVirtual.Domain.AggregateRoot.Usuario", "UsuarioCriacao")
                        .WithMany()
                        .HasForeignKey("UsuarioCriacaoId");

                    b.Navigation("UsuarioAtualizacao");

                    b.Navigation("UsuarioCriacao");
                });

            modelBuilder.Entity("EscritorioVirtual.Domain.AggregateRoot.Maps.Map", b =>
                {
                    b.HasOne("EscritorioVirtual.Domain.AggregateRoot.Usuario", "UsuarioAtualizacao")
                        .WithMany()
                        .HasForeignKey("UsuarioAtualizacaoId");

                    b.HasOne("EscritorioVirtual.Domain.AggregateRoot.Usuario", "UsuarioCriacao")
                        .WithMany()
                        .HasForeignKey("UsuarioCriacaoId");

                    b.Navigation("UsuarioAtualizacao");

                    b.Navigation("UsuarioCriacao");
                });

            modelBuilder.Entity("EscritorioVirtual.Domain.AggregateRoot.Usuario", b =>
                {
                    b.HasOne("EscritorioVirtual.Domain.AggregateRoot.Usuario", "UsuarioAtualizacao")
                        .WithMany()
                        .HasForeignKey("UsuarioAtualizacaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EscritorioVirtual.Domain.AggregateRoot.Usuario", "UsuarioCriacao")
                        .WithMany()
                        .HasForeignKey("UsuarioCriacaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UsuarioAtualizacao");

                    b.Navigation("UsuarioCriacao");
                });

            modelBuilder.Entity("EscritorioVirtual.Domain.AggregateRoot.Workspaces.Workspace", b =>
                {
                    b.HasOne("EscritorioVirtual.Domain.AggregateRoot.Usuario", "UsuarioAtualizacao")
                        .WithMany()
                        .HasForeignKey("UsuarioAtualizacaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EscritorioVirtual.Domain.AggregateRoot.Usuario", "UsuarioCriacao")
                        .WithMany()
                        .HasForeignKey("UsuarioCriacaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UsuarioAtualizacao");

                    b.Navigation("UsuarioCriacao");
                });

            modelBuilder.Entity("EscritorioVirtual.Domain.Aggregates.Chat.ChatChannelMember", b =>
                {
                    b.HasOne("EscritorioVirtual.Domain.AggregateRoot.Chat.ChatChannel", null)
                        .WithMany("Members")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EscritorioVirtual.Domain.Aggregates.Chat.ChatMessage", b =>
                {
                    b.HasOne("EscritorioVirtual.Domain.AggregateRoot.Chat.ChatChannel", null)
                        .WithMany("Messages")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EscritorioVirtual.Domain.Aggregates.Maps.MapObject", b =>
                {
                    b.HasOne("EscritorioVirtual.Domain.AggregateRoot.Maps.Map", null)
                        .WithMany("Objects")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EscritorioVirtual.Domain.Aggregates.Maps.MapZone", b =>
                {
                    b.HasOne("EscritorioVirtual.Domain.AggregateRoot.Maps.Map", null)
                        .WithMany("Zones")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EscritorioVirtual.Domain.Aggregates.Workspaces.WorkspaceInvite", b =>
                {
                    b.HasOne("EscritorioVirtual.Domain.AggregateRoot.Usuario", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EscritorioVirtual.Domain.AggregateRoot.Workspaces.Workspace", "Workspace")
                        .WithMany("Invites")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("EscritorioVirtual.Domain.Aggregates.Workspaces.WorkspaceUser", b =>
                {
                    b.HasOne("EscritorioVirtual.Domain.AggregateRoot.Usuario", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EscritorioVirtual.Domain.AggregateRoot.Workspaces.Workspace", "Workspace")
                        .WithMany("Members")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("EscritorioVirtual.Domain.AggregateRoot.Chat.ChatChannel", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("EscritorioVirtual.Domain.AggregateRoot.Maps.Map", b =>
                {
                    b.Navigation("Objects");

                    b.Navigation("Zones");
                });

            modelBuilder.Entity("EscritorioVirtual.Domain.AggregateRoot.Workspaces.Workspace", b =>
                {
                    b.Navigation("Invites");

                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
